import "server-only";
import { createHash } from "node:crypto";

/// Photos go straight from the citizen's phone to Cloudinary; the server only
/// signs the request. That keeps large uploads off the app server entirely,
/// which matters on the kind of connection this app is meant to work on.

export const UPLOAD_FOLDER = "civicpulse/complaints";

export function cloudinaryConfig() {
  const cloudName = process.env.CLOUDINARY_CLOUD_NAME;
  const apiKey = process.env.CLOUDINARY_API_KEY;
  const apiSecret = process.env.CLOUDINARY_API_SECRET;

  if (!cloudName || !apiKey || !apiSecret) return null;
  return { cloudName, apiKey, apiSecret };
}

export function isPhotoStorageConfigured(): boolean {
  return cloudinaryConfig() !== null;
}

/// Cloudinary's scheme: sort the signed params by key, join as a query string,
/// append the secret, SHA-1 the lot.
export function signUpload(params: Record<string, string | number>): {
  signature: string;
  timestamp: number;
  apiKey: string;
  cloudName: string;
  uploadUrl: string;
} | null {
  const config = cloudinaryConfig();
  if (!config) return null;

  const timestamp = Math.floor(Date.now() / 1000);
  const signed: Record<string, string | number> = { ...params, timestamp };

  const toSign = Object.keys(signed)
    .sort()
    .map((key) => `${key}=${signed[key]}`)
    .join("&");

  const signature = createHash("sha1")
    .update(toSign + config.apiSecret)
    .digest("hex");

  return {
    signature,
    timestamp,
    apiKey: config.apiKey,
    cloudName: config.cloudName,
    uploadUrl: `https://api.cloudinary.com/v1_1/${config.cloudName}/image/upload`,
  };
}

/// A client could POST any string as `photoUrl`, so the server only accepts
/// URLs that actually live in our own Cloudinary account and folder.
export function isOwnPhotoUrl(url: string): boolean {
  const config = cloudinaryConfig();
  if (!config) return false;

  let parsed: URL;
  try {
    parsed = new URL(url);
  } catch {
    return false;
  }

  return (
    parsed.protocol === "https:" &&
    parsed.hostname === "res.cloudinary.com" &&
    parsed.pathname.startsWith(`/${config.cloudName}/`) &&
    parsed.pathname.includes(UPLOAD_FOLDER)
  );
}

/// Thumbnail/display variants, generated by rewriting the delivery URL rather
/// than storing extra records. Keeps list pages light on slow connections.
export function photoVariant(
  url: string,
  variant: "thumb" | "card" | "full",
): string {
  if (!url.includes("/upload/")) return url;

  const transform =
    variant === "thumb"
      ? "c_fill,w_160,h_160,q_auto,f_auto"
      : variant === "card"
        ? "c_fill,w_640,h_400,q_auto,f_auto"
        : "c_limit,w_1600,q_auto,f_auto";

  return url.replace("/upload/", `/upload/${transform}/`);
}
